spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  profiles:
    active: dev
chenquan:
  test: ${CHEN_QUAN:meiyouzhi}