version: '3'
services:
#  nginx:
#   container_name: v-nginx
#   image: nginx:1.13
#   restart: always
#   ports:
#   - 80:80
#   - 443:443
#   volumes:
#   - ./nginx/conf.d:/etc/nginx/conf.d
    
  mysql:
   container_name: v-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
    CHEN_QUAN: chenquan_test
   ports:
   - "3306:3306"
   restart: always
   volumes:
   - ./mysql/db:/var/lib/mysql
   - ./mysql/conf/my.cnf:/etc/my.cnf
   - ./mysql/init:/docker-entrypoint-initdb.d/

  redis:
   container_name: v-redis
   image: redis
   command: redis-server /usr/local/etc/redis/redis.conf
   ports:
   - "6379:6379"
   restart: always
   volumes:
   - ./redis/db:/data
   - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

#  pt-shop-front:
#    build: ./ptShopFront
#    restart: always
#    depends_on:
#      - nginx
#      - mysql
#      - redis
#    ports:
#    - "8082:8082"

#  pt-shop-black:
#    build: ./ptShopBlack
#    restart: always
#    depends_on:
#      - nginx
#      - mysql
#      - redis
#    ports:
#    - "8084:8084"